# docker-compose.yaml
version: '3'

services:
  api:
    image: flask-api-test
    container_name: flask-api-test
    entrypoint: '/app/entrypoint.test.sh'
    command: pytest /app/tests/
    build: 'flask-api/'
    ports:
      - '5002:5000'
    environment:
      PYTHONPATH: /app
    volumes:
      - ./flask-api:/app
    env_file: ./flask-api/.env.test
    depends_on:
      - db
  db:
    image: postgres:16
    container_name: otd-db-test
    ports:
      - '5433:5432'
    env_file: ./flask-api/.env.test
