# docker-compose.yaml
version: '3'

services:
  web:
    image: flask-api-test
    container_name: flask-api-test
    ports:
      - '5001:5000'
    environment:
      PYTHONPATH: /app
    volumes:
      - flask-api:/app