# docker-compose.yaml
version: '3'

services:
  api:
    image: flask-api
    container_name: flask-api
    build: '../flask-api'
    ports:
      - '5001:5000'
    environment:
      PYTHONPATH: /app
    volumes:
      - ../flask-api:/app
    env_file: ../flask-api/.env