# docker-compose.yaml
version: '3'

services:
  api:
    image: flask-api
    container_name: flask-api
    build: '../flask-api'
    ports:
      - '5001:5000'
    environment:
      PYTHONPATH: /app
    volumes:
      - ../flask-api:/app
    env_file: ../flask-api/.env
    depends_on:
      - db
  db:
    image: postgres:16
    volumes:
      - ../flask-api/db_data:/var/lib/postgresql/data
    env_file: ../flask-api/.env  
volumes:
  db_data:
