# docker-compose.yaml
version: '3'

services:
  web:
    image: flask-api-test
    container_name: flask-api-test
    build: 
      context: ../flask-api
    ports:
      - '5002:5000'
    environment:
      PYTHONPATH: /app
    volumes:
      - ../flask-api:/app