name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v3
  
    - name: Install Docker
    # You may pin to the exact commit or the version.
    # uses: papodaca/install-docker-action@6689d765bf69e0b79e9352e11203caf4acd1d25c
      uses: papodaca/install-docker-action@v1
          
      
    - name: Build the Docker image
      run: docker compose -f docker/compose.dev.yaml up -d
      

    - name: Run Tests
      run: docker exec flask-api /bin/sh -c "pytest"
