name: Docker Image CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:

  Build-Test:
    environment: ci
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Lint
      run: |
        # TODO move lint inside docker container, so we don't install deps twice
        python -m pip install --upgrade pip
        pip install -r ${{ github.workspace }}/flask-api/requirements.txt
        pylint --rcfile=.pylintrc flask-api/
    - name: Gather environment variables
      run: |
        cat flask-api/.env.example > flask-api/.env.test
        # Read secrets from Github. Unfortunately, each secret needs to be
        # set manually
        sed -i 's/ENV_TYPE=.*/ENV_TYPE=${{ secrets.ENV_TYPE }}/' flask-api/.env.test
        sed -i 's/SECRET_KEY=.*/SECRET_KEY=${{ secrets.SECRET_KEY }}/' flask-api/.env.test
    - name: Build and Run Tests
      run: docker compose -f compose.ci.yaml up --abort-on-container-exit

  Audit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: gh-action-pip-audit
      uses: pypa/gh-action-pip-audit@v1.0.8
      with:
        inputs: flask-api/requirements.txt

    
