name: Docker Image CI

on:
  push:
    branches: ["dev", "main"]
  pull_request:
    branches: ["dev", "main"]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Runner Setup
        run: ./runner_setup.sh
      - name: Build
        run: docker compose -f docker/compose.dev.yaml up -d

      - name: Run Tests
        run: docker exec flask-api /bin/sh -c "pytest"
